use mavenmovies;

/*
MY PARTNER AND I WANT TO COME BY EACH OF THE STORES IN PERSON AND MEET THE MANGERS. PLEASE
SEND OVER THE MANAGERS' NAMES AT EACH STORE, WITH THE FULL ADDRESS OF EACH PROPERTY(STREET 
ADDRESS, DISTRICT, CITY AND COUNTRY PLEASE). 
*/

SELECT 
	STORE.STORE_ID,
	CONCAT(STAFF.FIRST_NAME,' ',STAFF.LAST_NAME) AS STORE_MANAGER,
	ADDRESS.ADDRESS,
    ADDRESS.DISTRICT,
    CITY.CITY,
    COUNTRY.COUNTRY
FROM STORE
LEFT JOIN STAFF ON STORE.MANAGER_STAFF_ID = STAFF.STAFF_ID
LEFT JOIN ADDRESS ON STORE.ADDRESS_ID = ADDRESS.ADDRESS_ID
LEFT JOIN CITY ON ADDRESS.CITY_ID = CITY.CITY_ID
LEFT JOIN COUNTRY ON CITY.COUNTRY_ID = COUNTRY.COUNTRY_ID;

/*
I WOULD LIKE TO GET A BETTER UNDERSTANDING OF ALL THE INVENTORY THAT WOULD COME ALONG WITH THE
BUSINESS. PLEASE PULL TOGETHER A LIST OF EACH INVENTORY ITEM YOU HAVE STOCKED, INCLUDING THE
STORE_ID NUMBER, THE INVENTORY_ID, THE NAME OF THE FILM'S RATING, ITS RENTAL RATE AND REPLACEMENT
COST. 
*/

SELECT 
	STORE_ID, 
	INVENTORY_ID, 
	RATING,
    RENTAL_RATE,
    REPLACEMENT_COST
FROM INVENTORY 
LEFT JOIN FILM ON FILM.FILM_ID = INVENTORY.FILM_ID;

/*
FROM THE SAME LIST OF FILMS YOU JUST PULLED, PLEASE ROLL THAT DATA UP AND PROVIDE A
SUMMARY LEVEL OVERVIEW OF YOUR INVENTORY. WE WOULD LIKE TO KNOW HOW MANY INVENTORYY ITEM
YOU HAVE WITH EACH RATING AT EACH STORE
*/

SELECT 
	STORE_ID, 
	RATING,
    COUNT(INVENTORY_ID) as INVENTORY_ITEM
FROM INVENTORY 
LEFT JOIN FILM ON FILM.FILM_ID = INVENTORY.FILM_ID
GROUP BY STORE_ID, RATING
ORDER BY STORE_ID, RATING;


/*
SIMILARLY, WE WANT TO UNDERSTAND HOW DIVERSIFIED THE INVENTORY IS IN TERMS OF REPLACEMENT COST. 
WE WANT TO SEE HOW BIG OF A HIT IT WOULD BE IF A CERTAIN CATEGORY OF FILM BECAME UNPOPULAR AT
A CERTAIN STORE. WE WOULD LIKE TO SEE THE NUMBER OF FILMS, AS WELL AS THE AVERAGE REPLACEMENT 
COST AND TOTAL REPLACEMENT COST, SLICED BY STORE AND FILM CATEGORY. 
*/

SELECT 
	STORE_ID, 
	category.NAME AS FILM_CATEGORY,
    COUNT(FILM.FILM_ID) AS NUMBER_OF_FILMS,
    AVG(REPLACEMENT_COST) AS AVERAGE_REPLACEMENT_COST,
    SUM(REPLACEMENT_COST) AS TOTAL_REPLACEMENT_COST
FROM INVENTORY 
LEFT JOIN FILM ON FILM.FILM_ID = INVENTORY.FILM_ID
LEFT JOIN film_category ON film_category.FILM_ID = FILM.FILM_ID
LEFT JOIN category ON film_category.category_id = category.category_id
GROUP BY STORE_ID, film_category;


/*
WE WANT TO MAKE SURE YOU FOLKS HAVE A GOOD HANDLE ON WHO YOUR CUSTOMERS ARE. PLEASE PROVIDE
A LIST OF ALL CUSTOMER NAMES, WHICH STORE THEY GO TO WHETHER OR NOT THEY ARE CURRENTLY ACTIVE,
AND THEIR FULL ADDRESSES -- STREET ADDRESS, CITY AND COUNTRY
*/

SELECT 
	CUSTOMER.FIRST_NAME,
    CUSTOMER.LAST_NAME,
	STORE_ID,
    CONCAT(	ADDRESS.ADDRESS,' ',
    CITY.CITY,' ',
    COUNTRY.COUNTRY) AS FULL_ADDRESS,
    ACTIVE
FROM CUSTOMER
LEFT JOIN ADDRESS ON CUSTOMER.ADDRESS_ID = ADDRESS.ADDRESS_ID
LEFT JOIN CITY ON ADDRESS.CITY_ID = CITY.CITY_ID
LEFT JOIN COUNTRY ON CITY.COUNTRY_ID = COUNTRY.COUNTRY_ID;

/*
WE WOULD LIKE TO UNDERSTOOD HOW MUCH YOUR CUSTOMER ARE SPENDING WITH YOU, AND ALSO TO KNOW
WHO YOUR MOST VALUABLE CUSTOMERS ARE. PLEASE PULL TOGETHER A LIST OF CUSTOMER NAMES, THEIR
TOTAL LIFETIME RENTALS, AND THE SUM OF ALL PAYMENTS YOU HAVE COLLECTED FROM THEM. IT WOULD 
BE GREAT TO SEE THIS ORDERED ON TOTAL LIFETIME VALUE, WITH THE MOST VALUABLE CUSTOMERS AT 
TOP OF THE LIST. 
*/

SELECT 
	CUSTOMER.FIRST_NAME,
    CUSTOMER.LAST_NAME,
    COUNT(RENTAL.RENTAL_ID) AS TOTAL_LIFETIME_RENTALS,
    SUM(AMOUNT) AS PAYMENTS
FROM CUSTOMER
LEFT JOIN RENTAL ON RENTAL.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
LEFT JOIN PAYMENT ON RENTAL.RENTAL_ID = PAYMENT.RENTAL_ID
GROUP BY 
	CUSTOMER.FIRST_NAME,
    CUSTOMER.LAST_NAME
ORDER BY 
	PAYMENTS DESC;
/*
MY PARTNER AND I WOULD LIKE TO GET TO KNOW YOUR BOARD OF ADVISORS AND ANY CURRENT INVESTORS.
COULD YOU PLEASE PROVIDE A LIST OF ADVISOR NAMES IN ONE TABLE? COULD YOU PLEASE NOTE WHETHER
THEY ARE AN INVESTOR OR AN ADVISOR, AND FOR THE INVESTORS, IT WOULD BE GOOD TO INCLUDE
WHICH COMPANY THEY WORK WITH. 
*/
SELECT 'ADVISOR' AS INVESTOR_OR_ADVISOR, first_name,last_name, 'NULL' AS COMPANY_NAME FROM advisor
UNION
SELECT 'INVESTOR' AS INVESTOR_OR_ADVISOR, first_name,last_name, company_name  AS COMPANY_NAME FROM investor;

/*
WE'RE INTERESTED IN HOW WELL YOU HAVE COVERED THE MOST-AWARDED ACTORS. OF ALL THE ACTORS WITH
THREE TYPES OF AWARDS, FOR WHAT % OF THEM DO WE CARRY A FILM? AND HOW ABOUT FOR ACTORS WITH TWO
TYPES OF AWARDS? SAME QUESTIONS. FINALLY, HOW ABOUT ACTORS WITH JUST ONE AWARD?
*/

select 
	case when actor_award.awards = 'Emmy, Oscar, Tony ' then '3'
    when actor_award.awards in ('Emmy, Oscar','Emmy, Tony','Oscar, Tony') then '2'
    else '1'
    end as no_of_awards,
    avg(case when actor_award.actor_id is null then 0 else 1 end) as percentage
from actor_award 
group by no_of_awards




